### PR TITLE
Add portuguese language to muss

### PR DESCRIPTION
**Pull request by AssisRaphael**
In this PR I adapt the muss to the Portuguese language. In addition, it adds documentation informing how the process of adapting the code to the new language was, which steps were taken and I present some values of time and computational cost required ([PortugueseModel_en.md](https://github.com/AssisRaphael/muss-ptBR/blob/main/documentations/PortugueseModel_en.md)).

### CODE REVIEW

**Comment by louismartin** [comment]
Amazing, thanks a lot for the PR!

**Comment by louismartin** [comment]
Will there be a publication associated with this model?

**Comment by louismartin** [comment]
If so we can add a pointer to it in the readme.

**Comment by AssisRaphael** [comment]
Thank you very much for accepting the PR. I'm still in the process of publishing my article on the use of muss for textual simplifications in Portuguese. As soon as I publish the article, I'll do another PR by adding it to the readme.

**Pull request merged**
